version: "3.9"
services:
postgres:
image: postgres:15
environment:
POSTGRES_USER: hunter
POSTGRES_PASSWORD: hunter
POSTGRES_DB: hunter
ports:
- "5432:5432"
healthcheck:
test: ["CMD-SHELL", "pg_isready -U hunter -d hunter"]
interval: 5s
timeout: 3s
retries: 10
